/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from './IERC20'
export type { IWETH } from './IWETH'
export type { SplitMain } from './SplitMain'

export { IERC20__factory } from './factories/IERC20__factory'
export { IWETH__factory } from './factories/IWETH__factory'
export { SplitMain__factory } from './factories/SplitMain__factory'
